services:
  postgres:
    container_name: postgres_go_homework
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2181090
      PGDATA: /data/postgres_homework
    volumes:
      - ./postgres-data:/data/postgres_homework
    ports:
      - "5432:5432"